### ISSUE TITLE
Unable to continue playing the game after a player has refreshed the game

### ISSUE THREAD

**Issue by ahmedsatti101** [BurakPetro/nc_group_project_ok_game#17]
![image](https://github.com/BurakPetro/nc_group_project_ok_game/assets/71497768/0f1a1c56-29b5-4b41-af63-76cb6d9143ae)

If a player has refreshed their game they won't be able to move their pieces or any other piece.

**Comment by deankiwi** [comment]
This is due to gridPostion not being updating when getting board back. Will need to update

```js client
  moveSpriteByName(spriteName, newX, newY) {
    const spriteToMove = this.children.list.find((child) => {
      return child.name === spriteName;
    });
    // TODO set gridPosition player to player and player to true
    if (spriteToMove) {
      spriteToMove.setPosition(newX, newY);
      spriteToMove.disableInteractive();
    } else {
      console.log(`Sprite with name ${spriteName} not found`);
    }
  } 
  ```

**Comment by deankiwi** [comment]
video of it not working.

recreate problem:
- go to game already set up e.g. testRoom4
- try to move tile

https://github.com/BurakPetro/nc_group_project_ok_game/assets/28204292/8e3a8897-38ed-4467-ac19-25bd33446ad6
