### ISSUE TITLE
canATileGoInThisLocation in ExampleScene.js is using the number 17 and not the variable gridSize 

### ISSUE THREAD

**Issue by deankiwi** [BurakPetro/nc_group_project_ok_game#18]
line 226 and 232

<img width="593" alt="image" src="https://github.com/BurakPetro/nc_group_project_ok_game/assets/28204292/5a94f080-4753-43a7-b17c-4bd3c9086b6b">

also line 250 should be gridSize * gridSize
<img width="473" alt="image" src="https://github.com/BurakPetro/nc_group_project_ok_game/assets/28204292/906cd861-67e5-45b8-9afe-87c944963915">

**Comment by rsr83** [comment]
I correct this one, but the function checkFiveInARow is all based on the size, so I need to check this one as well
